"""create foods table

Revision ID: 435b75b9ba60
Revises: d59f23fa6411
Create Date: 2026-06-07 02:06:49.934410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '435b75b9ba60'
down_revision: Union[str, None] = 'd59f23fa6411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('foods', sa.Column('protein', sa.Float(), nullable=True))
    op.add_column('foods', sa.Column('carbs', sa.Float(), nullable=True))
    op.add_column('foods', sa.Column('fat', sa.Float(), nullable=True))
    op.add_column('foods', sa.Column('fiber', sa.Float(), nullable=True))
    op.create_unique_constraint(op.f('uq_foods_name'), 'foods', ['name'])
    op.drop_column('foods', 'carbohydrates_g')
    op.drop_column('foods', 'zinc_mg')
    op.drop_column('foods', 'fiber_g')
    op.drop_column('foods', 'vitamin_a_mcg')
    op.drop_column('foods', 'iron_mg')
    op.drop_column('foods', 'fat_g')
    op.drop_column('foods', 'calcium_mg')
    op.drop_column('foods', 'image_url')
    op.drop_column('foods', 'calories_per_100g')
    op.drop_column('foods', 'created_at')
    op.drop_column('foods', 'protein_g')
    op.drop_column('foods', 'local_name')
    op.drop_column('foods', 'vitamin_c_mg')
    op.drop_column('foods', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('vitamin_c_mg', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('local_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('protein_g', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('foods', sa.Column('calories_per_100g', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('calcium_mg', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('fat_g', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('iron_mg', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('vitamin_a_mcg', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('fiber_g', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('zinc_mg', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('foods', sa.Column('carbohydrates_g', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_foods_name'), 'foods', type_='unique')
    op.drop_column('foods', 'fiber')
    op.drop_column('foods', 'fat')
    op.drop_column('foods', 'carbs')
    op.drop_column('foods', 'protein')
    op.drop_column('foods', 'calories')
    # ### end Alembic commands ###
