"""initial_schema

Revision ID: d59f23fa6411
Revises: 
Create Date: 2026-03-06 18:24:35.239657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59f23fa6411'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('local_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('calories_per_100g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbohydrates_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('vitamin_a_mcg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('vitamin_c_mg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('iron_mg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('calcium_mg', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('zinc_mg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_table('health_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('facility_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_workers'))
    )
    op.create_index(op.f('ix_health_workers_email'), 'health_workers', ['email'], unique=True)
    op.create_index(op.f('ix_health_workers_id'), 'health_workers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nutrition_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_children_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children'))
    )
    op.create_index(op.f('ix_children_id'), 'children', ['id'], unique=False)
    op.create_index(op.f('ix_children_user_id'), 'children', ['user_id'], unique=False)
    op.create_table('health_worker_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('health_worker_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['health_worker_id'], ['health_workers.id'], name=op.f('fk_health_worker_assignments_health_worker_id_health_workers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_health_worker_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_worker_assignments')),
    sa.UniqueConstraint('health_worker_id', 'user_id', name='uq_hw_assignment')
    )
    op.create_index(op.f('ix_health_worker_assignments_health_worker_id'), 'health_worker_assignments', ['health_worker_id'], unique=False)
    op.create_index(op.f('ix_health_worker_assignments_id'), 'health_worker_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_health_worker_assignments_user_id'), 'health_worker_assignments', ['user_id'], unique=False)
    op.create_table('daily_nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_protein_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('meals_count', sa.Integer(), nullable=True),
    sa.Column('nutrition_score', sa.Integer(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_daily_nutrition_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_nutrition')),
    sa.UniqueConstraint('child_id', 'date', name='uq_daily_nutrition_child_date')
    )
    op.create_index(op.f('ix_daily_nutrition_child_id'), 'daily_nutrition', ['child_id'], unique=False)
    op.create_index(op.f('ix_daily_nutrition_id'), 'daily_nutrition', ['id'], unique=False)
    op.create_table('growth_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('head_circumference_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('muac_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_growth_records_child_id_children'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_growth_records'))
    )
    op.create_index(op.f('ix_growth_records_child_id'), 'growth_records', ['child_id'], unique=False)
    op.create_index(op.f('ix_growth_records_id'), 'growth_records', ['id'], unique=False)
    op.create_index(op.f('ix_growth_records_recorded_date'), 'growth_records', ['recorded_date'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('image_url_before', sa.Text(), nullable=True),
    sa.Column('image_url_after', sa.Text(), nullable=True),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_time', sa.Time(), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('total_protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('nutrition_score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_meals_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index(op.f('ix_meals_child_id'), 'meals', ['child_id'], unique=False)
    op.create_index(op.f('ix_meals_id'), 'meals', ['id'], unique=False)
    op.create_index(op.f('ix_meals_meal_date'), 'meals', ['meal_date'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('nutrition_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], name=op.f('fk_nutrition_alerts_child_id_children'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nutrition_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_alerts'))
    )
    op.create_index(op.f('ix_nutrition_alerts_child_id'), 'nutrition_alerts', ['child_id'], unique=False)
    op.create_index(op.f('ix_nutrition_alerts_id'), 'nutrition_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_alerts_is_read'), 'nutrition_alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_nutrition_alerts_user_id'), 'nutrition_alerts', ['user_id'], unique=False)
    op.create_table('meal_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('portion_size_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('calories', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_meal_foods_food_id_foods'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_meal_foods_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_foods'))
    )
    op.create_index(op.f('ix_meal_foods_food_id'), 'meal_foods', ['food_id'], unique=False)
    op.create_index(op.f('ix_meal_foods_id'), 'meal_foods', ['id'], unique=False)
    op.create_index(op.f('ix_meal_foods_meal_id'), 'meal_foods', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_foods_meal_id'), table_name='meal_foods')
    op.drop_index(op.f('ix_meal_foods_id'), table_name='meal_foods')
    op.drop_index(op.f('ix_meal_foods_food_id'), table_name='meal_foods')
    op.drop_table('meal_foods')
    op.drop_index(op.f('ix_nutrition_alerts_user_id'), table_name='nutrition_alerts')
    op.drop_index(op.f('ix_nutrition_alerts_is_read'), table_name='nutrition_alerts')
    op.drop_index(op.f('ix_nutrition_alerts_id'), table_name='nutrition_alerts')
    op.drop_index(op.f('ix_nutrition_alerts_child_id'), table_name='nutrition_alerts')
    op.drop_table('nutrition_alerts')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_date'), table_name='meals')
    op.drop_index(op.f('ix_meals_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_child_id'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_growth_records_recorded_date'), table_name='growth_records')
    op.drop_index(op.f('ix_growth_records_id'), table_name='growth_records')
    op.drop_index(op.f('ix_growth_records_child_id'), table_name='growth_records')
    op.drop_table('growth_records')
    op.drop_index(op.f('ix_daily_nutrition_id'), table_name='daily_nutrition')
    op.drop_index(op.f('ix_daily_nutrition_child_id'), table_name='daily_nutrition')
    op.drop_table('daily_nutrition')
    op.drop_index(op.f('ix_health_worker_assignments_user_id'), table_name='health_worker_assignments')
    op.drop_index(op.f('ix_health_worker_assignments_id'), table_name='health_worker_assignments')
    op.drop_index(op.f('ix_health_worker_assignments_health_worker_id'), table_name='health_worker_assignments')
    op.drop_table('health_worker_assignments')
    op.drop_index(op.f('ix_children_user_id'), table_name='children')
    op.drop_index(op.f('ix_children_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_health_workers_id'), table_name='health_workers')
    op.drop_index(op.f('ix_health_workers_email'), table_name='health_workers')
    op.drop_table('health_workers')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
